development:
  adapter: postgresql
  encoding: unicode
  database: viel-centr_development
  pool: 15
test:
  adapter: postgresql
  encoding: unicode
  database: viel-centr_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: viel-centr_production
  pool: 15
  username: viel-centr
  password: 6yFC7HYW6FErhu6JQ
