development:
  adapter: postgresql
  encoding: unicode
  database: lytie_development
  pool: 15
test:
  adapter: postgresql
  encoding: unicode
  database: lytie_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: lytie_production
  pool: 15
  username: lytie
  password: 6yFC7HYW6FErhu6JQ
