development:
  adapter: postgresql
  encoding: unicode
  database: viel_development
  pool: 15
test:
  adapter: postgresql
  encoding: unicode
  database: viel_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: viel_production
  pool: 15
  username: viel
  password: 6yFC7HYW6FErhu6JQ
